### ISSUE TITLE
GHES auth issue? 

### ISSUE THREAD

**Issue by toddoconnor** [timrogers/gh-migration-audit#31]
When trying to run this against a GHES hosted org/repo for which I am an Org owner, I see this:

```
gh migration-audit audit-repo --access-token *** --owner ORGNAME --repo REPONAME  --base-url "https://URL/api/v3"

2023-11-10T19:02:12.062Z error: Error checking GitHub rate limit: fetch failed
RequestError12 [HttpError]: fetch failed
    at /snapshot/dist/migration-audit.cjs
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Job.doExecute (/snapshot/dist/migration-audit.cjs) {
  status: 500,
  request: {
    method: 'GET',
    url: 'https://URL/api/v3/meta',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit.js/3.1.1 octokit-core.js/5.0.0 Node.js/18.5.0 (darwin; x64)',
      authorization: 'token [REDACTED]'
    },
    request: {
      fetch: [Function: customFetch],
      hook: [Function: bound bound register]
    }
  }
}
```

Just accessing https://URL/api/v3/meta says this. Same for 3.9.5.

```
{
  "verifiable_password_authentication": false,
  "installed_version": "3.7.17"
}
``` 

Thanks
Todd

**Comment by timrogers** [comment]
That's weird! I have tested against GHES, so I suspect some kind of networking related issue. 

For debugging, how easy would it be for you to run this Node.js project directly rather than using the built binary? 

If you're able to do that, I'd suggest setting up a Zoom call and we can debug together live. 

One gap in this tool right now is verbose logging for GitHub API requests. I haven't added that because I can't figure out how to do it in the GitHub SDK. I'm going to try to figure that out today.

**Comment by timrogers** [comment]
@toddoconnor Can you try the new `--verbose` option in [v0.4.0](https://github.com/timrogers/gh-migration-audit/releases/tag/v0.4.0)? That might give us some more context on what's wrong here.

**Comment by timrogers** [comment]
Closing this as it's a long time ago now - feel free to re-open if you're still having issues.
